# required by security colleagues
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Expect-CT = "max-age=86400, enforce"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), interest-cohort=(), magnetometer=(), microphone=(), midi=(), payment=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "base-uri 'self'; block-all-mixed-content; default-src 'self' https: 'unsafe-eval' 'unsafe-inline'; font-src 'self' https://use.fontawesome.com data:; form-action 'self'; frame-ancestors 'self'; img-src 'self' data: *.openstreetmap.org https://unpkg.com; script-src-elem 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://code.jquery.com https://stackpath.bootstrapcdn.com https://www.google-analytics.com https://cdn.bootcss.com data:; sandbox allow-forms allow-popups allow-same-origin allow-scripts"
    # new stuff
    Content-Security-Policy = "base-uri 'self'; default-src 'self' https:  data: 'unsafe-eval' 'unsafe-inline'; font-src 'self' https://use.fontawesome.com data:; form-action 'self'; frame-ancestors 'self'; object-src 'self'; sandbox allow-downloads allow-forms allow-popups allow-same-origin allow-scripts; upgrade-insecure-requests"
    Cache-Control = "no-cache, max-age=0"
    Expires = "0"
    Pragma = "no-cache"
